import { SocialPost } from '../types';

export const INITIAL_SOCIAL_POSTS: SocialPost[] = [
  {
    id: 'sp-1',
    platform: 'twitter',
    handle: '@engr_buradum',
    authorName: 'Engr. Buradum Baribefe Daniel',
    authorAvatarUrl: '/assets/images/official-poster.png',
    verified: true,
    content: 'Inspiring session today with over 400 youth leaders, engineering students, and artisans at Bori-Ogoni. We must transition our brilliant youth from political bystanders into technological and industrial builders. Khana and Gokana will lead the new dawn of grassroots productivity. #LetsBuildAsOne #TheBeaconOfHope2027 #KhanaGokana2027 #NNPP',
    mediaUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80',
    mediaType: 'image',
    publishedAt: '2026-09-19T06:30:00Z',
    timeAgo: '1 hr ago',
    location: 'Bori, Khana LGA',
    likesCount: 542,
    sharesCount: 189,
    commentsCount: 76,
    postUrl: 'https://x.com/engr_buradum',
    tags: ['YouthEmpowerment', 'BoriOgoni', 'LetsBuildAsOne', 'NNPP']
  },
  {
    id: 'sp-2',
    platform: 'facebook',
    handle: 'buradumdaniel',
    authorName: 'Engr. Buradum Baribefe Daniel (Official)',
    authorAvatarUrl: '/assets/images/official-poster.png',
    verified: true,
    content: 'STRATEGIC PLANNING & YOUTH EMPOWERMENT IN BORI: Earlier today at the Bori Civic Center, our campaign leadership met with youth representatives, students, and community stakeholders. We unpacked our legislative blueprint for tech vocational incubators, micro-credit access, and local content job placement across Khana and Gokana. Together, we are building a constituency where our youth lead from the front.',
    mediaUrl: '/assets/images/bori-youth-empowerment-workshop.jpg',
    mediaType: 'image',
    publishedAt: '2026-09-18T18:45:00Z',
    timeAgo: 'Yesterday',
    location: 'Bori Civic Center, Khana LGA',
    likesCount: 890,
    sharesCount: 312,
    commentsCount: 145,
    postUrl: 'https://facebook.com/buradumdaniel',
    tags: ['BoriOgoni', 'YouthEmpowerment', 'KhanaGokana2027', 'LetsBuildAsOne']
  },
  {
    id: 'sp-3',
    platform: 'instagram',
    handle: '@engr_buradum',
    authorName: 'Engr. Buradum Baribefe Daniel',
    authorAvatarUrl: '/assets/images/official-poster.png',
    verified: true,
    content: 'Clean water is not a luxury; it is a fundamental human right. As a certified engineer, my top legislative priority in the Green Chamber will be expediting genuine, audited UNEP ecological remediation and durable municipal borehole networks across all 36 wards of Khana and Gokana. Together, we build for posterity. 💧🌿',
    mediaUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156f?auto=format&fit=crop&w=1000&q=80',
    mediaType: 'image',
    publishedAt: '2026-09-17T14:15:00Z',
    timeAgo: '2 days ago',
    location: 'Khana Remediation Axis',
    likesCount: 1240,
    sharesCount: 205,
    commentsCount: 98,
    postUrl: 'https://instagram.com/engr_buradum',
    tags: ['WaterRemediation', 'OgoniEnvironment', 'EngineeringLeadership']
  },
  {
    id: 'sp-4',
    platform: 'youtube',
    handle: '@engr_buradum',
    authorName: 'Engr. Buradum Official Channel',
    authorAvatarUrl: '/assets/images/official-poster.png',
    verified: true,
    content: 'WATCH: "The 5 Pillars of Hope" — Keynote Address delivered by Engr. Buradum Baribefe Daniel at the Khana/Gokana NNPP Constituency Unity Convention in Bori. Full speech highlights our infrastructure masterplan, bursaries for polytechnic students, and agricultural value-chain development.',
    mediaUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=80',
    mediaType: 'video',
    publishedAt: '2026-09-16T11:00:00Z',
    timeAgo: '3 days ago',
    location: 'Constituency Campaign Secretariat, Bori',
    likesCount: 2310,
    sharesCount: 520,
    commentsCount: 310,
    postUrl: 'https://youtube.com/@engr_buradum',
    tags: ['KeynoteAddress', 'LetUsBuildAsOne', 'HouseOfReps2027']
  },
  {
    id: 'sp-5',
    platform: 'twitter',
    handle: '@engr_buradum',
    authorName: 'Engr. Buradum Baribefe Daniel',
    authorAvatarUrl: '/assets/images/official-poster.png',
    verified: true,
    content: 'Hearty congratulations to our campaign volunteer teams who completed door-to-door civic sensitization in Ward 07 Babbe and Ward 04 Gokana over the weekend. Over 1,200 voters verified their polling unit status. Democracy works when the grassroots organize! #GrassrootsPower #NNPP',
    mediaUrl: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=1000&q=80',
    mediaType: 'image',
    publishedAt: '2026-09-15T09:20:00Z',
    timeAgo: '4 days ago',
    location: 'Babbe Ward 07, Khana LGA',
    likesCount: 715,
    sharesCount: 234,
    commentsCount: 88,
    postUrl: 'https://x.com/engr_buradum',
    tags: ['GrassrootsMobilization', 'WardVoters', 'NNPPRivers']
  },
  {
    id: 'sp-6',
    platform: 'tiktok',
    handle: '@engr_buradum',
    authorName: 'Engr. Buradum Official',
    authorAvatarUrl: '/assets/images/official-poster.png',
    verified: true,
    content: 'Behind the scenes: Candidate Q&A on why engineering oversight in the House of Representatives ensures that federal budget allocations for roads and solar grids actually get built to high technical standards. 🛠️⚡ #EngineersInPolitics #RiversState #OgoniYouth',
    mediaUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1000&q=80',
    mediaType: 'video',
    publishedAt: '2026-09-14T16:00:00Z',
    timeAgo: '5 days ago',
    location: 'Khana/Gokana Campaign Office',
    likesCount: 3450,
    sharesCount: 680,
    commentsCount: 240,
    postUrl: 'https://tiktok.com/@engr_buradum',
    tags: ['EngineersInGovernance', 'AskTheCandidate', 'KhanaGokana']
  }
];
